# Site settings
title: The Vows
email: mnem@noiseandheat.com
description: >
    Tracker for The Vows offered from the main political
    parties to keep Scotland in the Union.
baseurl: "/the-vows" # the subpath of your site, e.g. /blog/
url: "http://the-vows.github.com" # the base hostname & protocol for your site
twitter_username: kaeladan
github_username: mnem

# Build settings
markdown: kramdown
exclude: ["bower_components", "Rakefile", "README.md", "Gemfile", "Gemfile.lock"]
